#!/bin/bash
alias cl='clear; ls'

alias ll='ls -la'
alias ls='ls -G --color=auto'
alias cd..='cd ..'
alias vi='vim'
alias svi='sudo vi'
alias vim="vim -u $USR_HOME/.vimrc"
alias vis='vim "+set si"'
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
