#!/bin/bash

function wrkon(){
  if [ ! $1 ]
  then
    echo -e 'wrkon options:'
    echo -e '   list'
    echo -e '   exit'
    echo -e '   new <repo> [alias]'
    echo -e '   <repo> <alias>'
    echo -e '   <job>'
  elif [ "$1" == "list" ]
  then
    repos_str=`ls -cdr $HOME/.wrkon/*`
    repos=(${repos_str// /})
    printf '\t%-8s %-50s %-25s\n' "job" "repo" "alias"
    i=1
    for d in ${repos[*]}
    do
      tmp=(${d//:/ })
      tmp1=(${tmp[0]//\// })
      printf '\t%-8s %-50s %-25s\n' "[$i]" "${tmp1[${#tmp1[@]}-1]}" "${tmp[1]}"
      i=$(($i+1))
    done
  elif [ "$1" == "exit" ]
  then
    echo "Saying I'm exiting, but not really doing anything"
  elif [ "$1" == "new" ]
  then
    if [ "$2" == "" ]
    then
      echo "please provide wrkon-new with a repo"
      echo "correct command is 'wrkon <repo> [alias]'"
    else
      if [ "$3" == "" ]
      then
        echo "no alias"
        max=1
        #get the existing numeric aliases.... do the next one
        repos_str=`ls -d $HOME/.wrkon/$2:*`
        repos=(${repos_str// /})
        for d in ${repos[*]}
        do
          tmp=(${d//:/ })
          if [[ ${tmp[1]} != *[!0-9]* ]]
          then
            if [ ${tmp[1]} > $max ]
            then
              max=${tmp[1]}
            fi
          fi
        done
        max=$(($max + 1))
        echo $max
        mkdir $HOME/.wrkon/$2:$max
        cd $HOME/.wrkon/$2:$max
      else
        if [ -d "$HOME/.wrkon/$2:$3" ]
        then
          echo "$2:$3 exists, please select a different alias"
        else
          mkdir $HOME/.wrkon/$2:$3
          cd $HOME/.wrkon/$2:$3
        fi
      fi
    fi
  else
    if [[ $1 != *[!0-9]* ]]
    then
      echo $1
      repos_str=`ls -cdr $HOME/.wrkon/*`
      repos=(${repos_str// /})
      echo ${#repose[@]}
      if [ $(($1)) -ge ${#repos[@]} ]
      then
        echo "$1 is too large of a job number"
      else
        cd ${repos[$(($1-1))]}
      fi
    elif [ "$2" == "" ]
    then
      echo "Please provide an alias"
      echo "wrkon <repo> <alias>"
    else
      if [ -d "$HOME/.wrkon/$1:$2" ]
      then
        cd $HOME/.wrkon/$1:$2
      else
        echo "repo:alias '$1:$2' not found"
      fi
    fi
  fi
}
