#!/bin/bash

function wrkon(){
  if [ ! $1 ]
  then
    echo -e 'wrkon options:'
    echo -e '   list'
    echo -e '   exit'
    echo -e '   new <repo> [alias]'
    echo -e '   <repo> <alias>'
    echo -e '   <job>'
  elif [ "$1" == "list" ]
  then
    repos_str=`find $USR_HOME/.wrkon/ -maxdepth 1 -type d | sort | tail -n +2`
    repos=(${repos_str// /})
    printf '%-8s %-30s %-20s %-11s\n' "job" "repo" "alias" "active GUAC"
    i=1
    for d in ${repos[*]}
    do
      tmp=(${d//@/ })
      tmp1=(${tmp[0]//\// })
      if [ -d "${d}" ]
      then
        active=""
        if [ "$CURR_GUAC" == "${tmp[1]}" ] && [ "${tmp1[${#tmp1[@]}-1]}" == "GUAC" ]
        then
          active="*"
        fi
        printf '%-8s %-30s %-20s %-11s\n' "[$i]" "${tmp1[${#tmp1[@]}-1]}" "${tmp[1]}" "$active"
        i=$(($i+1))
      fi
    done
  elif [ "$1" == "exit" ]
  then
    #do the other stuff, too!
    export PS1=[$MACH_NAME]$POST_PS1
    export HOME=$USR_HOME
    export CURR_GUAC=''
    cd $HOME
  elif [ "$1" == "new" ]
  then
    if [ "$2" == "" ]
    then
      echo "please provide wrkon-new with a repo"
      echo "correct command is 'wrkon <repo> [alias]'"
    else
      if [ "$3" == "" ]
      then
        echo "no alias"
        max=0
        #get the existing numeric aliases.... do the next one
        repos_str=`ls -d $USR_HOME/.wrkon/$2@* 2>/dev/null`
        repos=(${repos_str// /})
        for d in ${repos[*]}
        do
          tmp=(${d//@/ })
          if [[ ${tmp[1]} != *[!0-9]* ]]
          then
            if [ ${tmp[1]} > $max ]
            then
              max=${tmp[1]}
            fi
          fi
        done
        max=$(($max + 1))
        git clone git@github.com:aunalytics/$2.git $USR_HOME/.wrkon/$2@$max
        cd $USR_HOME/.wrkon/$2@$max
        export HOME=$USR_HOME/.wrkon/$2@$max
          if [ "$2" == "GUAC" ]
          then
            source $USR_HOME/.wrkon/env.source
            export CURR_GUAC=$max
          fi
          export PS1=[$MACH_NAME][$2@$max]$POST_PS1
      else
        if [ -d "$USR_HOME/.wrkon/$2@$3" ]
        then
          echo "$2:$3 exists, please select a different alias"
        else
          git clone git@github.com:aunalytics/$2.git $USR_HOME/.wrkon/$2@$3
          cd $USR_HOME/.wrkon/$2@$3
          export HOME=$USR_HOME/.wrkon/$2@$3
          if [ "$2" == "GUAC" ]
          then
            source $USR_HOME/.wrkon/env.source
            export CURR_GUAC=$3
          fi
          export PS1=[$MACH_NAME][$2@$3]$POST_PS1
        fi
      fi
    fi
  else
    if [[ $1 != *[!0-9]* ]]
    then
      repos_str=`find $USR_HOME/.wrkon/ -maxdepth 1 -type d | sort | tail -n +2`
      repos=(${repos_str// /})
      if [ $(($1-1)) -ge ${#repos[@]} ] || [ $1 -lt 1 ]
      then
        echo "$1 is an illegal job number"
      else
        export HOME=${repos[$(($1-1))]}
        tmp1=(${repos[$(($1-1))]//\// })
        tmp2=(${tmp1[${#tmp1[@]}-1]//@/ })
        cd ${repos[$(($1-1))]}
        if [ "${tmp2[0]}" == "GUAC" ]
        then
          source $USR_HOME/.wrkon/env.source
          export CURR_GUAC=${tmp2[1]}
        fi
        export PS1=[$MACH_NAME][${tmp1[${#tmp1[@]}-1]}]$POST_PS1
      fi
    elif [ "$2" == "" ]
    then
      echo "Please provide an alias"
      echo "wrkon <repo> <alias>"
    else
      if [ -d "$USR_HOME/.wrkon/$1@$2" ]
      then
        cd $USR_HOME/.wrkon/$1@$2
        export HOME=$USR_HOME/.wrkon/$1@$2
        if [ "$1" == "GUAC" ]
        then
          source $USR_HOME/.wrkon/env.source
          export CURR_GUAC=$2
        fi
        export PS1=[$MACH_NAME][$1@$2]$POST_PS1
      else
        echo "repo:alias '$1@$2' not found"
      fi
    fi
  fi
}
